### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by chcg**
- added appveyor config, see corresponding https://ci.appveyor.com/project/jsleroy/compare-plugin/build/1.5.7.59
- added x64 build target for vs2013 vcxproj + adaptations
- minimal necessary code adapations for x64 (there are still > 100 x64 compiler warnings open due to conversion issues

### CODE REVIEW

**Comment by pnedev** [comment]
Hello @chcg,

Thank you for helping with this.

BR

**Comment by chcg** [comment]
Your welcome.
Issues apart from the compiler warnings:
- this PR just updates the VS2013 project, but not VS2015 one. Typically VS2015 and VS15 Preview 4 could load also the VS2013 version and automatically adapt the platform toolset from v120_xp -> v140_xp. So maybe VS2015 could be consider obsolete and deleted. What do you think? 
- Should I prepare some PR with a readme.md with some build instructions, the appveyor badge and the version history from ReleaseNotes.txt?
- What is the current status of the mingw cmake build?
- Maybe some x64 issues are still part of the compiler warnings

**Comment by pnedev** [comment]
Hello again,

- About VS2015 - perhaps you are right and it is not needed. I cannot say for sure because I don't have VS2015. I remember that some people had problems compiling on VS2015 before xylographe made the VS2015 project. Let's keep it for now, I'll modify VS2015 project file for x64 some time in the future.

- I'm not very familiar with Appveyor but yes, if you'd like to make readme.md useful in whatever way you find suitable please do so, thanks.

- Well, I made the CMake build for my own convenience. I'm working on Linux most of the time so I needed a way to compile the plugin so I could test my changes. I don't consider the CMake build a "Release" alternative to VS and I currently have no plans to update it for x64. Perhaps some time in the future.

- I'll check this some time soon when I find some free time but thanks again for the contribution.

BR

**Comment by pnedev** [comment]
FYI, @xylographe just added the necessary x64 VS2015 project modifications.

BR

**Pull request merged**
