### PR TITLE
Lib update

### PR DESCRIPTION
**Pull request by chcg**
- updated libgit2 to version 0.24.2 and added x64 variant from https://ci.appveyor.com/project/chcg/libgit2/build/6
- updated libgit2 to version 3.14.2 and added x64 variant from
https://sqlite.org/2016/sqlite-dll-win32-x86-3140200.zip
and
https://sqlite.org/2016/sqlite-dll-win64-x64-3140200.zip

### CODE REVIEW

**Comment by pnedev** [comment]
Thank you @chcg .
I'll merge your PR as soon as I verify the changes.

BR

**Comment by pnedev** [comment]
Hello @chcg ,

LibGit2 v0.24.2 does not work with CP for some reason.
That's why I've added Git2.dll v0.24.0 (both x86 and x64) and added it together with your SQLite3.dll (x86 and x64) to another commit. Thank you for the help.
This PR is not needed anymore.

BR

**Comment by chcg** [comment]
@pnedev Nice to see. Where did you get the git2.dlls from? I searched the net for some prebuild ones, but didn't find official ones.

In the meantime https://sqlite.org/releaselog/3_15_0.html was released.

Maybe interesting due to:

Miscellaneous micro-optimizations reduce CPU usage by more than 7% on common workloads. Most optimization in this release has been on the front-end (sqlite3_prepare_v2()).

**Comment by pnedev** [comment]
@chcg ,
I compiled git2.dll v0.24 myself from its released source snapshot. I used the minimal release build as the functionality CP uses is very limited.

About sqlite3, well, the new release might be interesting if it reduces the CPU time that much.

**Comment by chcg** [comment]
@pnedev 

Checked out what was the problem with libgit 0.24.2. Issue caused by libgit commit:
Revision: a200dc9e1d35d44aabda468966933f34dc7b702e
Author: Josh Triplett <josh@joshtriplett.org>
Date: 04.04.2016 04:24:15
Message:
Fix repository discovery with ceiling_dirs at current directory


git only checks ceiling directories when its search ascends to a parent
directory.  A ceiling directory matching the starting directory will not
prevent git from finding a repository in the starting directory or a
parent directory.  libgit2 handled the former case correctly, but
differed from git in the latter case: given a ceiling directory matching
the starting directory, but no repository at the starting directory,
libgit2 would stop the search at that point rather than finding a
repository in a parent directory.

Test case using git command-line tools:

/tmp$ git init x
Initialized empty Git repository in /tmp/x/.git/
/tmp$ cd x/
/tmp/x$ mkdir subdir
/tmp/x$ cd subdir/
/tmp/x/subdir$ GIT_CEILING_DIRECTORIES=/tmp/x git rev-parse --git-dir
fatal: Not a git repository (or any of the parent directories): .git
/tmp/x/subdir$ GIT_CEILING_DIRECTORIES=/tmp/x/subdir git rev-parse --git-dir
/tmp/x/.git

Fix the testsuite to test this case (in one case fixing a test that
depended on the current behavior), and then fix find_repo to handle this
case correctly.

In the process, simplify and document the logic in find_repo():
- Separate the concepts of "currently checking a .git directory" and
  "number of iterations left before going further counts as a search"
  into two separate variables, in_dot_git and min_iterations.
- Move the logic to handle in_dot_git and append /.git to the top of the
  loop.
- Only search ceiling_dirs and find ceiling_offset after running out of
  min_iterations; since ceiling_offset only tracks the longest matching
  ceiling directory, if ceiling_dirs contained both the current
  directory and a parent directory, this change makes find_repo stop the
  search at the parent directory.
----
Modified: src/repository.c
Modified: tests/repo/discover.c
Modified: tests/repo/open.c

which enforces the usage of a path as input to gitLib->repository_open_ext(), but we are providing a absolute path with filename. Unclear if this was an intentional sideeffect or not.

**Comment by pnedev** [comment]
Hi Christian,

Great, thanks.
We are using a very small part of the Git library and its upgrade is not essential but nevertheless it is good to fix the code so it is compatible with whatever version of libgit2 we are working with.
I'll do it as soon as I have finished the change I'm working on unless you haven't done it already :)

BR

**Comment by chcg** [comment]
Hi,

I did some work on this here:

https://github.com/chcg/compare-plugin/commit/bc5e445a455b60a24f786df19e94c6aa6c55992e

I think the most interesting parts of the updated libgit2 are not feature related but the security fixes.
The fix still works with the currently used git version 024.0.

The other things is the postbuild action to copy the git and sqlite dlls from within VS studio nd some optimizations of the settings.

 I would like to extend that also to the cmake build.

**Comment by pnedev** [comment]
@chcg 

Hi Christian,

> I think the most interesting parts of the updated libgit2 are not feature related but the security fixes.

Indeed, I agree.

> Should I also add a compiled version of 0.24.3?

Please do. The latest libgit2.dll version should be readily available from its AppVeyor build, correct?

The post-build lib copy action is great addition and your change looks fine overall but could you please reuse `ansiPath` buffer instead of adding `ansiPathPlusFilename` inside the `if (!gitLib->repository_open_ext(&repo, ansiPath, 0, NULL))` body?
Could you also please add post-build lib copy action for the x86 variant? I didn't see it in the change but I might have missed it.

Thank you.

BR

**Comment by chcg** [comment]
@pnedev 

- See e.g. https://ci.appveyor.com/project/libgit2/libgit2/build/2876, libgit itself just builds the checkins, but doesn't store artifacts. Furthermore they use VS 2011. So I took the tag created a branch, modified appveyor config and end up with the build:

https://ci.appveyor.com/project/chcg/libgit2/build/9

with artifacts.

- Ok,I will change it to reuse the buffer.
- Seems you are right. Thought I already added the postbuild to both debug builds. I will correct that.
- maybe added copy action for cmake, if it is working

**Comment by pnedev** [comment]
Thanks Christian.

**Pull request closed without merging**
