### PR TITLE
added initial version of markdown readme

### PR DESCRIPTION
**Pull request by chcg**
See https://github.com/chcg/compare-plugin/tree/readme how it looks like

### CODE REVIEW

**Comment by xylographe** [comment]
Perhaps, mention "Git Diff", "SVN Diff" and "Diff since last Save" in first section? (features?)

Perhaps, replace the Changelog section with a link to `ReleaseNotes.txt`?

Remove *Sourceforge* link? (old versions)
Official releases via [GitHub?](https://github.com/jsleroy/compare-plugin/releases) (for those who cannot build CP themselves, recent beta DLLs are available at [Dropbox,](https://www.dropbox.com/sh/f42cxkqppuapa1j/AADvlcmqoK_myRmoOpeL1yGMa?dl=0) and, of course, through the [AppVeyor artifacts.](https://ci.appveyor.com/project/jsleroy/compare-plugin/history))

**Comment by pnedev** [comment]
Hi @chcg ,

I agree with @xylographe on the first two points he mentions (about adding the features "Git Diff", "SVN Diff" and "Diff since last Save" in first section and replacing the Changelog section with a link to _ReleaseNotes.txt_).

I think the Sourceforge link can be left for now as there is still no official v2 release (I want to fix the remaining issues before doing that). So it can be kept as official releases link but anyway, it will be good to point to the beta/development releases as well -> Dropbox and AppVeyor as @xylographe points out.

Thank you both.

BR

**Comment by chcg** [comment]
OK. I will update the PR.

**Comment by pnedev** [comment]
Thank you @chcg .

BR

**Pull request merged**
