### PR TITLE
travis beta vm

### PR DESCRIPTION
**Pull request by chcg**
- test travis build with faster to init docker beta vm, see https://docs.travis-ci.com/user/trusty-ci-environment/
- @pnedev maybe also of interest for you is automatic deployment, see e.g. https://github.com/ashkulz/NppFTP/blob/master/.travis.yml, this would be also possible from the appveyor build, if needed

Travis Build 113:

Elapsed time 41 sec
Total time 1 min 17 sec

Travis Build 114 of this PR:

Elapsed time 54 sec
Total time 1 min 42 sec

, also startup: 21.068041909s -> startup: 1.109403687s

### CODE REVIEW

**Comment by pnedev** [comment]
Thanks Christian.

BR

**Comment by chcg** [comment]
@pnedev 

Hi Pavel,
maybe you didn't see my hidden question:
 
maybe also of interest for you is automatic deployment, see e.g. https://github.com/ashkulz/NppFTP/blob/master/.travis.yml, this would be also possible from the appveyor build, if needed. It is also possible to manually start the deploy, instead of the automatic one for each tag.

Are you interested in such a solution?

Regards,
 Christian

**Comment by pnedev** [comment]
Hi Christian,

I must have missed your question, sorry for that.
I was thinking about automatic deployment before, yes. I would like to make it for AppVeyor build for each new tag and I would like it to be for both build variants - 32 and 64 bit. I would also like it to be in a form of zip archive containing the plugin dll + all additional libraries for the corresponding build variant.

Do you think that's possible?
It would certainly be of great help when releasing a new plugin version officially.

Thank you.

BR

**Comment by chcg** [comment]
Hi Pavel,

yes, that should be possible, which version do you want for the official deploy VS2015 (slightly bigger also just the platformtoolset differs) or VS2013?

**Comment by pnedev** [comment]
Hi Christian,

Looks very nice, thank you, great work.
I prefer VS2013, thanks.

BR

**Pull request merged**
